{
 "title": "Vector Index",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Vector Index Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "vector_index_size",
     "legendFormat": "{{class_name}} / {{shard_name}}"
    }
   ]
  },
  {
   "title": "Vector Index Maintenance Operations (Sync & Async)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(vector_index_maintenance_durations_ms_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Insert Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(vector_index_durations_ms_sum{operation=\"create\"}[5s])/rate(vector_index_durations_ms_count{operation=\"create\"}[5s])",
     "legendFormat": "{{step}} ({{class_name}}/{{shard_name}})"
    }
   ]
  },
  {
   "title": "Delete Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(vector_index_durations_ms_sum{operation=\"delete\"}[5s])/rate(vector_index_durations_ms_count{operation=\"delete\"}[5s])",
     "legendFormat": "{{step}} ({{class_name}}/{{shard_name}})"
    }
   ]
  }
 ]
}